22:18:20.389 INFO Test execution started: test_page/add_description
22:18:20.389 INFO Browser: chrome
22:18:20.390 INFO Environment: test
22:18:20.390 INFO Using data: 
    description: description of the test
    url: http://localhost:8000

22:18:22.434 INFO Navigate to: 'http://localhost:8000'
22:18:22.539 INFO Write 'admin' in element username
22:18:22.615 INFO Write 'admin' in element password
22:18:22.652 INFO Click login_button
22:18:23.170 INFO Random value generated: zwacrfj
22:18:23.170 INFO Store value zwacrfj in key name
22:18:43.841 INFO Write 'zwacrfj' in element None
22:18:43.841 INFO Press key: ENTER
22:18:43.931 INFO Click None
22:18:44.229 INFO Write 'description of the test' in element description
22:18:44.264 INFO Click save
22:18:44.405 INFO Refresh page
22:18:44.435 INFO Verify element 'description' contains text 'description of the test'
22:18:44.451 INFO Take screenshot error
22:18:45.015 ERROR An error ocurred:
Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/test_runner/test_runner.py", line 115, in run_test
    test_module.test(execution.data)
  File "/Users/lucianofeo/Desktop/golem/example/projects/golem/tests/test_page/add_description.py", line 20, in test
    verify_text_in_element(test_page.description, data.description)
  File "/Users/lucianofeo/Desktop/golem/src/golem/actions.py", line 372, in verify_text_in_element
    .format(text, webelement.name))
golem.core.exceptions.TextNotPresent: Text 'description of the test' was not found in element description
22:18:45.016 INFO Close driver
