21:07:06.455 INFO Test execution started: project/add_directory_to_pages
21:07:06.456 INFO Browser: chrome
21:07:06.456 INFO Environment: test
21:07:06.456 INFO Using data: 
    url: http://localhost:8000

21:07:08.501 INFO Navigate to: 'http://localhost:8000'
21:07:08.598 INFO Write 'admin' in element username
21:07:08.673 INFO Write 'admin' in element password
21:07:08.708 INFO Click login_button
21:07:09.130 INFO Random value generated: dbbeq
21:07:09.131 INFO Store value dbbeq in key directory_name
21:07:09.363 INFO Write 'dbbeq/' in element None
21:07:09.363 INFO Press key: ENTER
21:07:09.379 INFO Waiting for 3 seconds
21:07:12.409 INFO Assert that 0 equals 1
21:07:12.411 INFO Take screenshot error
21:07:12.956 ERROR An error ocurred:
Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/test_runner/test_runner.py", line 115, in run_test
    test_module.test(execution.data)
  File "/Users/lucianofeo/Desktop/golem/example/projects/golem/tests/project/add_directory_to_pages.py", line 17, in test
    project.verify_page_directory_exists(data.directory_name)
  File "/Users/lucianofeo/Desktop/golem/example/projects/golem/pages/project.py", line 100, in verify_page_directory_exists
    actions.assert_equals(len(tree_elements), 1)
  File "/Users/lucianofeo/Desktop/golem/src/golem/actions.py", line 56, in assert_equals
    raise Exception('Expected {} to equal {}'.format(actual_value, expected_value))
Exception: Expected 0 to equal 1
21:07:12.956 INFO Close driver
