18:19:03.097 INFO Test execution started: test_page.add_action_to_test
18:19:03.098 INFO Browser: chrome-headless
18:19:03.098 INFO Environment: test
18:19:06.867 INFO Using data: 
    action: capture
    url: http://localhost:8000

18:19:14.130 INFO Navigate to: 'http://localhost:8000'
18:19:16.738 INFO Write 'admin' in element username
18:19:16.892 INFO Write 'admin' in element password
18:19:17.017 INFO Click login_button
18:19:28.791 INFO Click None
18:19:32.006 INFO Click #testSteps button.add-step
18:19:33.026 INFO Write 'capture' in element None
18:19:33.026 INFO Press key: DOWN
18:19:33.125 INFO Press key: ENTER
18:19:33.389 INFO Click save
18:19:33.634 INFO Refresh page
18:19:33.637 INFO Take screenshot error
18:19:36.012 ERROR An error ocurred:
Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/test_runner/test_runner.py", line 115, in run_test
    test_module.test(execution.data)
  File "/Users/lucianofeo/Desktop/golem/example/projects/golem/tests/test_page/add_action_to_test.py", line 18, in test
    refresh_page()
  File "/Users/lucianofeo/Desktop/golem/src/golem/actions.py", line 188, in refresh_page
    _capture_or_add_step(step_message, settings.settings['screenshot_on_step'])
NameError: name 'settings' is not defined
18:19:36.013 INFO Close driver
