2017-10-09 20:05:28,366 golem INFO Test execution started: project/add_page
2017-10-09 20:05:28,366 golem INFO Browser: chrome
2017-10-09 20:05:28,367 golem INFO Environment: test
2017-10-09 20:05:28,367 golem INFO Using data: 
    url: http://localhost:8000

2017-10-09 20:05:30,469 golem INFO Navigate to: 'http://localhost:8000'
2017-10-09 20:05:30,487 golem DEBUG Element found
2017-10-09 20:05:30,570 golem INFO Write 'admin' in element username
2017-10-09 20:05:30,588 golem DEBUG Element found
2017-10-09 20:05:30,652 golem INFO Write 'admin' in element password
2017-10-09 20:05:30,668 golem DEBUG Element found
2017-10-09 20:05:30,689 golem INFO Click login_button
2017-10-09 20:05:31,032 golem INFO Random value generated: iizyj
2017-10-09 20:05:31,033 golem INFO Store value iizyj in key page_name
2017-10-09 20:05:31,143 golem DEBUG Element found
2017-10-09 20:05:31,174 golem DEBUG Element found
2017-10-09 20:05:31,205 golem DEBUG Element found
2017-10-09 20:05:31,283 golem DEBUG Element found
2017-10-09 20:05:31,342 golem INFO Write 'iizyj' in element None
2017-10-09 20:05:31,342 golem INFO Press key: ENTER
2017-10-09 20:05:31,363 golem DEBUG Element found
2017-10-09 20:05:31,502 golem INFO Take screenshot error
2017-10-09 20:05:32,031 golem ERROR An error ocurred:
Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/test_runner/test_runner.py", line 115, in run_test
    test_module.test(execution.data)
  File "/Users/lucianofeo/Desktop/golem/example/projects/golem/tests/project/add_page.py", line 16, in test
    project.verify_page_exists('not')
  File "/Users/lucianofeo/Desktop/golem/example/projects/golem/pages/project.py", line 122, in verify_page_exists
    raise Exception('Page {} was not found'.format(dir_name))
Exception: Page not was not found
2017-10-09 20:05:32,031 golem INFO Close driver
