{
    "test_case": "checkout.checkout_initially_empty",
    "result": "fail",
    "steps": [
        "Navigate to: 'http://store.demoqa.com/'",
        "Click go_to_checkout",
        "error__0bc7f8aa"
    ],
    "description": "",
    "error": "Traceback (most recent call last):\n  File \"/Users/lucianofeo/Desktop/golem/src/golem/browser.py\", line 20, in _find_webelement\n    webelement = root.find_element_by_css_selector(selector_value)\n  File \"/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py\", line 509, in find_element_by_css_selector\n    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)\n  File \"/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py\", line 843, in find_element\n    'value': value})['value']\n  File \"/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py\", line 308, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py\", line 194, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.TimeoutException: Message: timeout\n  (Session info: headless chrome=61.0.3163.100)\n  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/lucianofeo/Desktop/golem/src/golem/test_runner/test_runner.py\", line 93, in run_test\n    test_module.test(execution.data)\n  File \"/Users/lucianofeo/Desktop/golem/example/projects/store_demoqa/tests/checkout/checkout_initially_empty.py\", line 13, in test\n    verify_text_in_element(checkout.items_container, 'Oops, there is nothing in your cart.')\n  File \"/Users/lucianofeo/Desktop/golem/src/golem/actions.py\", line 342, in verify_text_in_element\n    webelement = get_browser().find(element)\n  File \"/Users/lucianofeo/Desktop/golem/src/golem/browser.py\", line 113, in _find\n    element_name, timeout)\n  File \"/Users/lucianofeo/Desktop/golem/src/golem/browser.py\", line 47, in _find_webelement\n    .format(element_name, selector_type, selector_value))\ngolem.core.exceptions.ElementNotFound: Element items_container not found using selector css:'div.entry-content'\n",
    "short_error": "golem.core.exceptions.ElementNotFound: Element items_container not found using selector css:'div.entry-content'\n",
    "test_elapsed_time": 360.64,
    "test_timestamp": "2017.10.05.15.08.01.320",
    "browser": "chrome (headless)",
    "test_data": {}
}