21:01:20.354 INFO Test execution started: project/add_directory_to_pages
21:01:20.354 INFO Browser: chrome
21:01:20.354 INFO Environment: test
21:01:20.355 INFO Using data: 
    url: http://localhost:8000

21:01:22.373 INFO Navigate to: 'http://localhost:8000'
21:01:22.479 INFO Write 'admin' in element username
21:01:22.557 INFO Write 'admin' in element password
21:01:22.593 INFO Click login_button
21:01:23.003 INFO Random value generated: vvtll
21:01:23.003 INFO Store value vvtll in key directory_name
21:01:23.267 INFO Write 'vvtll/' in element None
21:01:23.268 INFO Press key: ENTER
21:01:23.287 INFO Waiting for 3 seconds
21:01:26.309 INFO Waiting for 10 seconds
21:01:36.327 INFO Assert that 0 equals 1
21:01:36.328 INFO Take screenshot error
21:01:36.855 ERROR An error ocurred:
Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/test_runner/test_runner.py", line 115, in run_test
    test_module.test(execution.data)
  File "/Users/lucianofeo/Desktop/golem/example/projects/golem/tests/project/add_directory_to_pages.py", line 17, in test
    project.verify_page_directory_exists(data.directory_name)
  File "/Users/lucianofeo/Desktop/golem/example/projects/golem/pages/project.py", line 102, in verify_page_directory_exists
    actions.assert_equals(len(tree_elements), 1)
  File "/Users/lucianofeo/Desktop/golem/src/golem/actions.py", line 56, in assert_equals
    raise Exception('Expected {} to equal {}'.format(actual_value, expected_value))
Exception: Expected 0 to equal 1
21:01:36.856 INFO Close driver
