21:23:05.884 INFO Test execution started: project.add_page_inside_directory
21:23:05.885 INFO Browser: chrome-headless
21:23:05.886 INFO Environment: test
21:23:05.886 INFO Using data: 
    url: http://localhost:8000

21:23:08.257 INFO Navigate to: 'http://localhost:8000'
21:23:08.392 INFO Write 'admin' in element username
21:23:08.532 INFO Write 'admin' in element password
21:23:08.599 INFO Click login_button
21:23:09.057 INFO Random value generated: jsmqa
21:23:09.058 INFO Store value jsmqa in key dir_name
21:23:09.058 INFO Random value generated: jqfnp
21:23:09.059 INFO Store value jqfnp in key page_name
21:23:09.607 INFO Write 'jsmqa/' in element None
21:23:09.608 INFO Press key: ENTER
21:23:09.628 INFO Take screenshot error
21:23:10.491 ERROR An error ocurred:
Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/test_runner/test_runner.py", line 115, in run_test
    test_module.test(execution.data)
  File "/Users/lucianofeo/Desktop/golem/example/projects/golem/tests/project/add_page_inside_directory.py", line 19, in test
    project.add_new_page(data.page_name, data.dir_name)
TypeError: add_new_page() takes 1 positional argument but 2 were given
21:23:10.491 INFO Close driver
